/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vendedores.client.view;

/**
 *
 * @author aevan
 */
public class InserirVendedoresView extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public InserirVendedoresView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtVendedor = new javax.swing.JTextField();
        lblVendedor = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        spnIdade = new javax.swing.JSpinner();
        lblTotalVendas = new javax.swing.JLabel();
        spnTotalVendas = new javax.swing.JSpinner();
        txtIdentificacaoVendaIC = new javax.swing.JTextField();
        lblIdentificacaoVendaIC = new javax.swing.JLabel();
        txtFilial = new javax.swing.JTextField();
        lblFilial = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        txtVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVendedorActionPerformed(evt);
            }
        });
        getContentPane().add(txtVendedor);
        txtVendedor.setBounds(110, 20, 330, 40);

        lblVendedor.setText("Vendedor:");
        getContentPane().add(lblVendedor);
        lblVendedor.setBounds(40, 30, 60, 16);

        lblIdade.setText("Idade:");
        getContentPane().add(lblIdade);
        lblIdade.setBounds(30, 90, 40, 10);
        getContentPane().add(spnIdade);
        spnIdade.setBounds(80, 90, 64, 20);

        lblTotalVendas.setText("Total de vendas:");
        getContentPane().add(lblTotalVendas);
        lblTotalVendas.setBounds(180, 90, 90, 16);

        spnTotalVendas.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        getContentPane().add(spnTotalVendas);
        spnTotalVendas.setBounds(290, 90, 160, 22);
        getContentPane().add(txtIdentificacaoVendaIC);
        txtIdentificacaoVendaIC.setBounds(180, 190, 260, 40);

        lblIdentificacaoVendaIC.setText("Identificação da venda(IC):");
        getContentPane().add(lblIdentificacaoVendaIC);
        lblIdentificacaoVendaIC.setBounds(30, 200, 150, 16);
        getContentPane().add(txtFilial);
        txtFilial.setBounds(70, 130, 340, 40);

        lblFilial.setText("Filial:");
        getContentPane().add(lblFilial);
        lblFilial.setBounds(30, 140, 40, 16);

        btnEnviar.setText("Enviar");
        getContentPane().add(btnEnviar);
        btnEnviar.setBounds(400, 300, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirVendedoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirVendedoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirVendedoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirVendedoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InserirVendedoresView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel lblFilial;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblIdentificacaoVendaIC;
    private javax.swing.JLabel lblTotalVendas;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JSpinner spnIdade;
    private javax.swing.JSpinner spnTotalVendas;
    private javax.swing.JTextField txtFilial;
    private javax.swing.JTextField txtIdentificacaoVendaIC;
    private javax.swing.JTextField txtVendedor;
    // End of variables declaration//GEN-END:variables
}
